### ISSUE TITLE
Config & Contract files are not copied when running node ace configure

### ISSUE THREAD

**Issue by irfancoder** [mezielabs/adonis-stripe#10]
## Description

Bug: Template `stripe.ts` files are not copied when running `node ace configure @mezielabs/adonis-stripe`

## Package version
adonis-stripe 1.0.4

## Error Message & Stack Trace
Error stack trace: 
```
node ace configure @mezielabs/adonis-stripe
...
UnhandledPromiseRejectionWarning: Error: Template file not found: <local-path>/node_modules/@mezielabs/adonis-stripe/build/templates/stripe.txt
```

Actual paths: `../templates/config/stripe.txt`  & `../templates/contracts/stripe.txt` 
## Relevant Information

I think you might've forgot to update the file paths in the command script. Anyway, I've resolved the issue by manually copy-pasting the two files into my project. And now it works fine! Thank you for the package

**Comment by ammezie** [comment]
This has been fixed in the latest release.
