### ISSUE TITLE
stripe as peer-dependency

### ISSUE THREAD

**Issue by irfancoder** [mezielabs/adonis-stripe#16]
## Description

Not a bug, but I recommend including `stripe` as a peer-dependency, not as dependency. When I installed your package, the installed stripe package is at `v8.222`, when the latest version currently is `v10.7` at the time of writing. 

Given that this is a wrapper package that provides a stripe singleton instance, I think this should be safe to implement.

## Package version
adonis-stripe: 1.0.5

**Comment by ammezie** [comment]
@irfancoder thanks for the recommendation. `stripe` is now a peer-dependency.
